[environments.default]
url="jdbc:postgresql://localhost:5434/examen_modulo_1_pb20002_vv18009"
user="postgres"
password="admin123"
schemas=["public"]

[flyway]
locations=["filesystem:sql", "filesystem:repeatable"]